# 테이블 작성 쿼리
CREATE TABLE board.Board (
	POSTID INT(200) AUTO_INCREMENT,
	TITLE varchar(1000) NOT NULL,
	WRITER varchar(100) NOT NULL,
	POSTDATE DATETIME NOT NULL,
	VIEWCOUNT varchar(100) NOT NULL,
	GRP INT(200),
	STATUS INT(200) DEFAULT 1 NOT NULL,
	SEQ INT(200),
	PRIMARY KEY (POSTID)
);
alter table Board add CONTENTS varchar(5000);
alter table Board AUTO_INCREMENT=0;

# 데이터 입력 쿼리
INSERT INTO Board (
	TITLE,
	WRITER,
	POSTDATE,
	VIEWCOUNT,
	CONTENTS,
	GRP,
	seq
) VALUES (
	'EXAMPLE 5234',
	'GWKIM',
	NOW(),
	0,
	'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
	LAST_INSERT_ID() + 1,
	1
);

truncate Board;
